#!/bin/bash
cat > LICENSE-THIRD-PARTY <<EOF
==============================================
             THIRD PARTY LICENSES
==============================================

**********************************************
            lib/rootbox/argparser
**********************************************

`cat lib/rootbox/argparser/LICENSE`
EOF

cp LICENSE* lib/rootbox
